---
namespace: lab
name: controller_demo_config
version: 6.0.0
authors:
  - Scott Harwell <sharwell@redhat.com>
description: A collection of content for setting up Ansible on Cloud demos rapidly.
documentation: ''
homepage: https://github.com/ansible-content-lab/aoc.controller_demo_config
issues: https://github.com/ansible-content-lab/aoc.controller_demo_config/issues
license_file: LICENSE
readme: README.md
repository: https://github.com/ansible-content-lab/aoc.controller_demo_config.git
tags:
  - cloud
  - azure
  - infrastructure
dependencies:
  ansible.controller: '>=4.4.0'
build_ignore:
  - '.tox'
  - '.git'
  - '.github'
  - '.gitignore'