---
- name: Validated Content - Azure web application deployment demo
  ansible.controller.job_template:
    name: Validated Content - Azure web application deployment demo
    job_type: run
    execution_environment: "{{ cloud_ee.id | int }}"
    project: "{{ validated_content_project_azure.id | int }}"
    playbook: playbooks/webapp.yml
    ask_credential_on_launch: true
    ask_inventory_on_launch: true
    ask_variables_on_launch: true
    extra_vars:
      azure.resource_group: "<deployment resource group>"
    become_enabled: false
    job_slice_count: 1
    state: present
  when:
    - (seed_validated_content | bool)
  register: web_application_demo
  tags:
    - templates
    - azure

- name: Validated Content - Azure web application migration demo
  ansible.controller.job_template:
    name: Validated Content - Azure web application migration demo
    job_type: run
    execution_environment: "{{ cloud_ee.id | int }}"
    project: "{{ validated_content_project_azure.id | int }}"
    playbook: playbooks/vmss_migrate.yml
    ask_credential_on_launch: true
    ask_inventory_on_launch: true
    ask_variables_on_launch: true
    extra_vars:
      source_resource_group: "<source resource group>"
      destination_resource_group: "<destination resource group>"
    become_enabled: false
    job_slice_count: 1
    state: present
  when:
    - (seed_validated_content | bool)
  register: web_migration_demo
  tags:
    - templates
    - azure
