---
- name: Validated Content - Google Cloud upload file to cloud storage
  ansible.controller.job_template:
    name: Validated Content - Google Cloud upload file to cloud storage
    job_type: run
    execution_environment: "{{ cloud_ee.id | int }}"
    project: "{{ validated_content_project_gcp.id | int }}"
    playbook: playbooks/upload_file_to_cloud_storage/upload_file_to_cloud_storage.yaml
    ask_credential_on_launch: true
    ask_inventory_on_launch: true
    ask_variables_on_launch: true
    extra_vars:
      upload_file_to_cloud_storage_bucket_name: ""
      upload_file_to_cloud_storage_file_path: ""
    become_enabled: false
    job_slice_count: 1
    state: present
  when:
    - (seed_validated_content | bool)
  register: aws_vm_migration
  tags:
    - templates
    - gcp

- name: Validated Content - Google Cloud move VM from on-prem to cloud
  ansible.controller.job_template:
    name: Validated Content - Google Cloud move VM from on-prem to cloud
    job_type: run
    execution_environment: "{{ cloud_ee.id | int }}"
    project: "{{ validated_content_project_gcp.id | int }}"
    playbook: playbooks/move_vm_from_on_prem_to_gcp/move_vm_from_on_prem_to_gcp.yml
    ask_credential_on_launch: true
    ask_inventory_on_launch: true
    ask_variables_on_launch: true
    extra_vars:
      clone_on_prem_vm_uri: "qemu:///system"
      clone_on_prem_vm_overwrite: true
      import_image_and_run_gcp_instance_zone: "us-central1-a"
      import_image_and_run_gcp_instance_machine_type: "n1-standard-1"
    become_enabled: false
    job_slice_count: 1
    state: present
  when:
    - (seed_validated_content | bool)
  register: aws_vm_migration
  tags:
    - templates
    - gcp
