---
- name: Add Red Hat Registry Credential
  ansible.controller.credential:
    name: "{{ credentials.red_hat_registry.name }}"
    description: Red Hat Registry
    organization: "{{ awx_organization }}"
    state: present
    credential_type: Container Registry
    inputs:
      host: registry.redhat.io
      username: "{{ lookup('env', 'RED_HAT_ACCOUNT') }}"
      password: "{{ lookup('env', 'RED_HAT_PASSWORD') }}"
  no_log: true
  when:
    - (seed_lab_content | bool) or (seed_validated_content | bool)
    - lookup('env', 'RED_HAT_ACCOUNT') is defined
    - lookup('env', 'RED_HAT_PASSWORD') is defined
  register: rh_credential
  tags:
    - credentials

- name: Add Azure Credential
  ansible.controller.credential:
    name: "{{ credentials.azure_service_principal.name }}"
    description: Azure Service Principal
    organization: "{{ awx_organization }}"
    state: present
    credential_type: Microsoft Azure Resource Manager
    inputs:
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      subscription: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      client: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
  no_log: true
  when:
    - (seed_lab_content | bool)
    - lookup('env', 'AZURE_TENANT') is defined
    - lookup('env', 'AZURE_SUBSCRIPTION_ID') is defined
    - lookup('env', 'AZURE_CLIENT_ID') is defined
    - lookup('env', 'AZURE_SECRET') is defined
    - credentials.azure_service_principal.name is defined
  register: azure_credential
  tags:
    - credentials
    - azure

- name: Add AWS Credential
  ansible.controller.credential:
    name: "{{ credentials.aws_account.name }}"
    description: AWS Account
    organization: "{{ awx_organization }}"
    state: present
    credential_type: Amazon Web Services
    inputs:
      username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      security_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default(omit) }}"
  no_log: true
  when:
    - (seed_lab_content | bool)
    - lookup('env', 'AWS_ACCESS_KEY_ID') is defined
    - lookup('env', 'AWS_SECRET_ACCESS_KEY') is defined
    - credentials.aws_account.name is defined
  register: aws_account
  tags:
    - credentials
    - aws

- name: Add VM SSH Credential
  ansible.controller.credential:
    name: "{{ credentials.ssh.name }}"
    description: SSH key for linux hosts
    organization: "{{ awx_organization }}"
    state: present
    credential_type: Machine
    inputs:
      username: "{{ credentials.ssh.user }}"
      ssh_key_data: "{{ credentials.ssh.key_data }}"
  no_log: true
  ignore_errors: true
  when:
    - (seed_lab_content | bool)
    - credentials.ssh.name is defined
    - credentials.ssh.user is defined
    - credentials.ssh.key_data is defined
  register: vm_credential
  tags:
    - credentials

- name: Add Ansible Automation Controller Credential
  ansible.controller.credential:
    name: "{{ credentials.controller.name }}"
    description: Credential for API calls to Ansible Controller
    organization: Default
    state: present
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
      username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
      password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
  no_log: true
  when:
    - (seed_lab_content | bool)
    - lookup('env', 'CONTROLLER_HOST') is defined
    - lookup('env', 'CONTROLLER_USERNAME') is defined
    - lookup('env', 'CONTROLLER_PASSWORD') is defined
  register: controller_credential
  tags:
    - credentials
