---
- name: Create Red Hat SSO credential type
  ansible.controller.credential_type:
    name: Red Hat SSO
    description: Single Sign On account for Red Hat Services
    kind: cloud
    inputs: "{{ lookup('file', 'rh_sso_inputs.yml') | from_yaml }}"
    injectors: "{{ lookup('file', 'rh_sso_injectors.yml') | from_yaml }}"
    state: present
    validate_certs: false
  tags:
    - credential_types
  register: rh_sso_credential_type
