---
- name: Add Red Hat Registry Credential
  ansible.controller.credential:
    name: Red Hat Registry
    description: Red Hat Registry
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: Container Registry
    inputs:
      host: registry.redhat.io
      username: "{{ lookup('env', 'RED_HAT_ACCOUNT') }}"
      password: "{{ lookup('env', 'RED_HAT_PASSWORD') }}"
  when:
    - (controller_seed_lab_content | bool) or (controller_seed_validated_content | bool)
    - lookup('env', 'RED_HAT_ACCOUNT') is defined
    - lookup('env', 'RED_HAT_PASSWORD') is defined
  register: rh_credential
  tags:
    - credentials

- name: Add Azure Credential
  ansible.controller.credential:
    name: Azure Service Principal
    description: Azure Service Principal
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: Microsoft Azure Resource Manager
    inputs:
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      subscription: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      client: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
  when:
    - (controller_seed_lab_content | bool)
    - lookup('env', 'AZURE_TENANT') is defined
    - lookup('env', 'AZURE_SUBSCRIPTION_ID') is defined
    - lookup('env', 'AZURE_CLIENT_ID') is defined
    - lookup('env', 'AZURE_SECRET') is defined
  register: azure_credential
  tags:
    - credentials
    - azure

- name: Add AWS Credential
  ansible.controller.credential:
    name: AWS Account
    description: AWS Account
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: Amazon Web Services
    inputs:
      username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      security_token: "{{ lookup('env', 'AWS_SESSION_TOKEN') | default(omit) }}"
  when:
    - (controller_seed_lab_content | bool)
    - lookup('env', 'AWS_ACCESS_KEY_ID') is defined
    - lookup('env', 'AWS_SECRET_ACCESS_KEY') is defined
  register: aws_account
  tags:
    - credentials
    - aws

- name: Add VM SSH Credential
  ansible.controller.credential:
    name: VM SSH Credential
    description: SSH key for linux hosts
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: Machine
    inputs:
      username: vmuser
      ssh_key_data: "{{ controller_credentials_ssh_key_data }}"
  when:
    - (controller_seed_lab_content | bool)
    - controller_credentials_ssh_key_data is defined
  register: vm_credential
  tags:
    - credentials

- name: Add Ansible Automation Controller Credential
  ansible.controller.credential:
    name: Ansible Automation Controller
    description: Credential for API calls to Ansible Controller
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
      username: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
      password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
  when:
    - (controller_seed_lab_content | bool)
    - lookup('env', 'CONTROLLER_HOST') is defined
    - lookup('env', 'CONTROLLER_USERNAME') is defined
    - lookup('env', 'CONTROLLER_PASSWORD') is defined
  register: controller_credential
  tags:
    - credentials

- name: Add Red Hat SSO Credential
  ansible.controller.credential:
    name: Red Hat SSO
    description: Red Hat SSO
    organization: "{{ controller_awx_organization }}"
    state: present
    credential_type: "{{ rh_sso_credential_type.id | int }}"
    controller_host: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    inputs:
      username: "{{ lookup('env', 'RED_HAT_ACCOUNT') }}"
      password: "{{ lookup('env', 'RED_HAT_PASSWORD') }}"
  register: red_hat_sso_credential
  tags:
    - credentials
