---
- name: Add EE Cloud Services Execution Environment
  ansible.controller.execution_environment:
    name: Cloud Services Execution Environment
    description: Red Hat Cloud Services EE
    organization: "{{ awx_organization | default('') }}"
    image: registry.redhat.io/ansible-automation-platform-24/
    credential: "{{ rh_credential.name }}"
    pull: always
    state: present
  register: cloud_services_ee
  when:
    - (seed_validated_content | bool)
  tags:
    - ees

- name: Set Cloud Services EE as global default
  ansible.builtin.set_fact:
    default_execution_environment: "{{ cloud_services_ee.id | int }}"
  when:
    - (seed_validated_content | bool)
    - cloud_services_ee.id is defined
  tags:
    - ees

- name: Add Test Cloud Execution Environment
  ansible.controller.execution_environment:
    name: Cloud Example EE
    description: Cloud Content Lab EE that contains dependencies for major hyperscaler collections.
    image: quay.io/scottharwell/cloud-ee:latest
    state: present
    pull: always
  register: cloud_ee
  when:
    - (seed_lab_content | bool)
  tags:
    - ees

- name: Set Cloud EE as global default
  ansible.builtin.set_fact:
    default_execution_environment: "{{ cloud_ee.id | int }}"
  when: 
    - (seed_lab_content | bool)
    - cloud_ee.id is defined
    - execution_environments.cloud_ee.set_default is defined
    - (execution_environments.cloud_ee.set_default | bool)
  tags:
    - ees
