---
- name: Delete Demo Project
  ansible.controller.project:
    name: Demo Project
    state: absent
  when:
    - (seed_lab_content | bool)
    - delete_demo_project is defined
    - (delete_demo_project | bool)
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Demo Project
  ansible.controller.project:
    name: "{{ projects.azure_demo_project.name }}"
    description: "{{ projects.azure_demo_project.name }}"
    default_environment: "{{ execution_environments.cloud_ee.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.azure_demo_project.url }}"
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_demo
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Project
  ansible.controller.project:
    name: "{{ projects.azure_lab_roles.name }}"
    description: "{{ projects.azure_lab_roles.name }}"
    default_environment: "{{ execution_environments.cloud_ee.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.azure_lab_roles.url }}"
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_azure
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Terraform Project
  ansible.controller.project:
    name: "{{ projects.azure_tf.name }}"
    description: "{{ projects.azure_tf.name }}"
    default_environment: "{{ execution_environments.cloud_ee.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.azure_lab_roles.url }}"
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_azure_tf
  tags:
    - projects
    - azure
    - terraform

- name: Add Ansible Cloud Content Lab AWS Project
  ansible.controller.project:
    name: "{{ projects.aws_lab_roles.name }}"
    description: "{{ projects.aws_lab_roles.name }}"
    default_environment: "{{ execution_environments.cloud_ee.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.aws_lab_roles.url }}"
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_aws
  tags:
    - projects
    - aws

- name: Add Ansible Cloud Seeded Content Project
  ansible.controller.project:
    name: "{{ projects.azure_seeded_content.name }}"
    description: "{{ projects.azure_seeded_content.name }}"
    default_environment: "{{ execution_environments.cloud_services.name }}"
    organization: "{{ awx_organization }}"  # Organization is required in projects
    scm_type: git
    scm_url: "{{ projects.azure_seeded_content.url }}"
    state: present
    update_project: true
    wait: true
  when:
    - (seed_validated_content | bool)
  register: seeded_content_project_azure
  tags:
    - projects
    - azure
