---
- name: Delete Demo Project
  ansible.controller.project:
    name: Demo Project
    state: absent
  when:
    - (seed_lab_content | bool)
    - delete_demo_project is defined
    - (delete_demo_project | bool)
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Demo Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - Ansible TMM Azure Content
    description: Example Azure content from the Ansible TMM team.
    default_environment: "{{ cloud_ee.name }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-cloud/azure.git
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_demo
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - Azure Content
    description: Example Azure content from the Ansible Content Lab for Cloud Automation.
    default_environment: "{{ cloud_ee.name }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_azure
  tags:
    - projects
    - azure

- name: Add Ansible Validated Content Project
  ansible.controller.project:
    name: Ansible Validated Content - Azure Demos
    description: Ansible validated content examples for Ansible on Azure.
    default_environment: "{{ execution_environments.cloud_services.name }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/redhat-cop/cloud.azure_ops.git
    state: present
    update_project: true
    wait: true
  when:
    - (seed_validated_content | bool)
  register: seeded_content_project_azure
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab AWS Deployment Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - AWS Deployment
    description: Collection that contains automation for deploying a self-managed AAP instance on AWS.
    default_environment: "{{ cloud_ee.name }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/aws_ansible_deployment.git
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_aws
  tags:
    - projects
    - aws

- name: Add Ansible Cloud Content Lab AWS Content Project
  ansible.controller.project:
    name: Ansible Cloud Content Lab - AWS Content
    description: Example AWS content from the Ansible Content Lab for Cloud Automation.
    default_environment: "{{ cloud_ee.name }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git
    state: present
    update_project: true
    wait: true
  when:
    - (seed_lab_content | bool)
  register: content_lab_project_aws
  tags:
    - projects
    - aws
