---
# Do not directly wait for projects. If you do, then you will not get the actual record ID back from the request.
- name: Delete Demo Project
  ansible.controller.project:
    name: Demo Project
    state: absent
  when:
    - (controller_seed_lab_content | bool)
    - delete_demo_project is defined
    - (delete_demo_project | bool)
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Demo Project
  ansible.controller.project:
    name: "{{ controller_projects_lab_azure_tmm_name }}"
    description: Example Azure content from the Ansible TMM team.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-cloud/azure.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (controller_seed_lab_content | bool)
  register: content_lab_project_demo
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab Azure Project
  ansible.controller.project:
    name: "{{ controller_projects_lab_azure_name }}"
    description: Example Azure content from the Ansible Content Lab for Cloud Automation.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/azure.infrastructure_config_demos.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (controller_seed_lab_content | bool)
  register: content_lab_project_azure
  tags:
    - projects
    - azure

- name: Add Ansible Cloud Content Lab AWS Deployment Project
  ansible.controller.project:
    name: "{{ controller_projects_lab_aws_deployment_name }}"
    description: Collection that contains automation for deploying a self-managed AAP instance on AWS.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/aws_ansible_deployment.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (controller_seed_lab_content | bool)
  register: content_lab_project_aws_deployment
  tags:
    - projects
    - aws

- name: Add Ansible Cloud Content Lab AWS Content Project
  ansible.controller.project:
    name: "{{ controller_projects_lab_aws_name }}"
    description: Example AWS content from the Ansible Content Lab for Cloud Automation.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/ansible-content-lab/aws.infrastructure_config_demos.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (controller_seed_lab_content | bool)
  register: content_lab_project_aws_content
  tags:
    - projects
    - aws

- name: Add AWS Validated Content Project
  ansible.controller.project:
    name: "{{ controller_projects_validated_aws_name }}"
    description: Ansible validated content examples for AWS.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/redhat-cop/cloud.aws_ops.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (seed_validated_content | bool)
  register: validated_content_project_aws
  tags:
    - projects
    - aws

- name: Add Azure Validated Content Project
  ansible.controller.project:
    name: "{{ controller_projects_validated_azure_name }}"
    description: Ansible validated content examples for Azure.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/redhat-cop/cloud.azure_ops.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (seed_validated_content | bool)
  register: validated_content_project_azure
  tags:
    - projects
    - azure

- name: Add Google Cloud Validated Content Project
  ansible.controller.project:
    name: "{{ controller_projects_validated_gcp_name }}"
    description: Ansible validated content examples for Google Cloud.
    default_environment: "{{ cloud_ee.id | int }}"
    organization: "{{ awx_organization }}" # Organization is required in projects
    scm_type: git
    scm_url: https://github.com/redhat-cop/cloud.gcp_ops.git
    state: present
    update_project: true
    wait: "{{ controller_projects_wait }}"
  when:
    - (seed_validated_content | bool)
  register: validated_content_project_gcp
  tags:
    - projects
    - gcp
