---
- name: Deploy Ansible Automation Controller Seeded Content
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Run Controller Configuration Role
      ansible.builtin.import_role:
        name: controller
