---
name: Validation CI

"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - assigned
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
      - review_requested

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements
        run: sudo pip3 install pre-commit

      - name: Copy ansible-lint config into dir
        shell: bash
        run: cp ./.ansible-lint /home/runner/.ansible/.ansible-lint

      - name: Ensure tmp dir exists
        shell: bash
        run: mkdir -p /home/runner/.ansible/tmp

      - name: Run pre-commit tests
        run: pre-commit run -v
